title: notification
preview: '@preview-bg'
status: prototype
variants:
  - name: error
    context:
      status: 'error'
      message: 'Something bad happened, please try again.'
      actionText: 'Refresh'
  - name: warning
    context:
      status: 'warning'
      message: 'Something bad might happen, check this.'
      actionText: 'Check thing'
  - name: info
    context:
      status: 'info'
      message: 'Here is some information'
  - name: finish
    context:
      status: 'finish'
      message: 'This is complete'
