title: 'color palette'
status: draft
context:
  colors:
    - color:
      colorName: 'red'
      colorCode: '#be4900'
    - color:
      colorName: 'blue'
      colorCode: '#056dd4'
    - color:
      colorName: 'gold'
      colorCode: '#f4b400'
    - color:
      colorName: 'green'
      colorCode: '#0baf00'
    - color:
      colorName: 'brightmint'
      colorCode: '#00df99'
    - color:
      colorName: 'cream'
      colorCode: '#f5f5f3'
    - color:
      colorName: 'trueblack'
      colorCode: '#000000'
    - color:
      colorName: 'textblack'
      colorCode: '#333333'
    - color:
      colorName: 'darkgray'
      colorCode: '#555555'
    - color:
      colorName: 'mediumgray'
      colorCode: '#8e8e8e'
    - color:
      colorName: 'mediumgray-trans'
      colorCode: 'rgba(0, 0, 0, .4)'
    - color:
      colorName: 'lightgray'
      colorCode: '#d3d3d3'
    - color:
      colorName: 'lightestgray'
      colorCode: '#f5f5f3'
    - color:
      colorName: 'white'
      colorCode: '#ffffff'
