title: count-status-grid
status: prototype
context:
  entityType: space
  status: alt
  entityCount: 1
variants:
  - name: default
  - name: space
    context:
      entityType: space
      entityCount: 3
  - name: app-none
    context:
      entityType: app
      entityCount: 0
      errors: 0
  - name: app-ok
    context:
      entityType: app
      entityCount: 4
      errors: 0
  - name: app-error
    context:
      entityType: app
      entityCount: 6
      errors: 2
  - name: app-error-xxl
    context:
      entityType: app
      entityCount: 16
      errors: 1
  - name: service-none
    context:
      entityType: service
      entityCount: 0
      errors: 0
  - name: service-ok
    context:
      entityType: service
      entityCount: 3
      errors: 0
  - name: service-error
    context:
      entityType: service
      entityCount: 3
      errors: 2
