variables:
  BUNDLER_VERSION: "2.2.20"
  NVM_VERSION: "v0.39.0"
  NODE_VERSION: "latest"
  NVM_DIR: "$HOME/.nvm"

stages:
  - lint
  - test
  - build
  - snapshot
  - visual_regression

default:
  image: cimg/ruby:3.1-browsers

before_script:
  - export BASH_ENV="$HOME/.bash.env"
  - gem install bundler --version $BUNDLER_VERSION
  - wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - . "$NVM_DIR/nvm.sh" --install --latest-npm
  - echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
  - echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
  - node -v


cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - ~/.npm
    - ~/.bundler

before_cache:
  script:
    - rm -f .bundler/ruby/2.6.0/cache/*.gem

.bundle-npm-install: &bundle_npm_install
  - gem install bundler --version $BUNDLER_VERSION
  - bundle check --path ~/.bundler || bundle install --path ~/.bundler
  - npm ci

build-docs:
  script:
    - *bundle_npm_install
    - make -j2 build-assets build-docs

snapshot:
  script:
    - scripts/snapshot.js
  artifacts:
    paths:
      - tmp/screenshot/branches

lints:
  stage: lint
  script:
    - *bundle_npm_install
    - make lint

integration:
  stage: test
  script:
    - *bundle_npm_install
    - npm test
  variables:
    SKIP_VISUAL_REGRESSION_TEST: "true"

snapshot-main:
  stage: snapshot
  script:
    - git checkout main
    - *bundle_npm_install
    - build-docs
    - snapshot
  except:
    - main

snapshot-branch:
  stage: snapshot
  script:
    - *bundle_npm_install
    - build-docs
    - snapshot
  except:
    - main

visual-regression:
  stage: visual_regression
  script:
    - *bundle_npm_install
    - cp -r tmp/screenshot/branches/* tmp/screenshot/branches/
    - npm test
  except:
    - main
  artifacts:
    paths:
      - tmp/screenshot/diff
    reports:
      junit: tmp/screenshot/diff

test:
  stage: test
  script:
    - *bundle_npm_install
    - npm test

# Workflows
# workflows:
#   version: 2
#   test:
#     jobs:
#       - lints
#       - integration
#   visual_regression:
#     jobs:
#       - snapshot-main:
#           rules:
#             - if: $CI_COMMIT_REF_NAME != "migration"
#       - snapshot-branch:
#           rules:
#             - if: $CI_COMMIT_REF_NAME != "migration"
#       - visual-regression:
#           rules:
#             - if: $CI_COMMIT_REF_NAME != "migration"
#           needs:
#             - snapshot-main
#             - snapshot-branch

