title: Login.gov Design System
description: A place for designers and developers to see components available for use on Login.gov sites.
github_repo_url: https://github.com/18F/identity-design-system

source: docs
destination: dist
keep_files:
  - assets

collections:
  components:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ''
    values:
      layout: base
