# Markdown config
markdown: redcarpet
highlighter: rouge

name: login.gov style guide

source: docs/build

include:
-  _theme

exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- src
- fractal.js

permalink: pretty

repos:
- name: login.gov style guide
  description: The global style of login.gov
  url: https://github.com/18F/identity-style-guide

collections:
  base:
    output: true
    permalink: /:path/
  components:
    output: true
    permalink: /:path/
