title: Login.gov Design System
description: A place for designers and developers to see components available for use on Login.gov sites.
github_repo_url: https://github.com/18F/identity-design-system

source: docs
destination: dist
keep_files:
  - assets

collections:
  components:
    output: true
    show_in_navigation: true
    permalink: /:name/
  embeds:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ''
    values:
      layout: component
