# Markdown config
markdown: redcarpet
highlighter: rouge

name: Login.gov style

source: docs/build

version: 0.4.0

include:
-  _theme

exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- src
- fractal.js

permalink: pretty

repos:
- name: Login.gov style
  description: The global style of login.gov.
  url: https://github.com/18F/identity-style-guide

collections:
  base:
    output: true
    permalink: /:path/
  components:
    output: true
    permalink: /:path/
