version: 2.1

commands:
  bundle-npm-install:
    steps:
      - restore_cache:
          key: dependency-cache-ruby-2-6-{{ checksum "package-lock.json" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Update Bundler
          command: gem install bundler -v "<2"
      - run:
          name: Install bundle dependencies
          command: bundle check --path ~/.bundler || bundle install --path ~/.bundler
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-ruby-2-6-{{ checksum "package-lock.json" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.npm
            - ~/.bundler
  build:
    steps:
      - run:
          name: Build assets and site
          command: npm run build

jobs:
  lints:
    working_directory: ~/identity-style-guide
    docker:
      - image: circleci/ruby:2.6-node-browsers
    steps:
      - checkout
      - bundle-npm-install
      - run:
          name: Lint JavaScript and Sass
          command: npm run lint
  integration:
    working_directory: ~/identity-style-guide
    docker:
      - image: circleci/ruby:2.6-node-browsers
    environment:
      SKIP_VISUAL_REGRESSION_TEST: true
    steps:
      - checkout
      - bundle-npm-install
      - build
      - run:
          name: Run jest integration test
          command: npm run test-jest
  visual-regression:
    working_directory: ~/identity-style-guide
    docker:
      - image: circleci/ruby:2.6-node-browsers
    environment:
      ONLY_VISUAL_REGRESSION_TEST: true
    steps:
      - checkout
      - bundle-npm-install
      - build
      - run:
          name: Run visual regression test
          command: npm run test-jest
      - store_artifacts:
          path: tmp/results
          destination: results
      - store_test_results:
          path: tmp/results
  accessibility:
    working_directory: ~/identity-style-guide
    docker:
      - image: circleci/ruby:2.6-node-browsers
    steps:
      - checkout
      - bundle-npm-install
      - build
      - run:
          name: Run pa11y accessibility test
          command: npm run test-pa11y
      - store_artifacts:
          path: tmp/results
          destination: results
      - store_test_results:
          path: tmp/results

workflows:
  version: 2
  test:
    jobs:
      - lints
      - integration
      - visual-regression
      - accessibility
