version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8
  node: circleci/node@5.2.0
  ruby: circleci/ruby@2.1.2

commands:
  build-docs:
    steps:
      - run:
          name: Build assets and site
          command: make -j2 build-assets build-docs
  snapshot:
    steps:
      - run:
          name: Generate snapshots
          command: scripts/snapshot.js
      - persist_to_workspace:
          root: tmp/screenshot/branches
          paths:
            - '*'

jobs:
  lints:
    docker:
      - image: cimg/ruby:3.3-browsers
    steps:
      - checkout
      - node/install
      - node/install-packages
      - run:
          name: Lint JavaScript, Sass, and lockfiles
          command: make lint
  integration:
    docker:
      - image: cimg/ruby:3.3-browsers
    environment:
      SKIP_VISUAL_REGRESSION_TEST: true
    steps:
      - checkout
      - node/install
      - node/install-packages
      - ruby/install-deps
      - run:
          name: Run integration tests
          command: npm test
  snapshot-main:
    docker:
      - image: cimg/ruby:3.3-browsers
    steps:
      - checkout
      - run:
          name: Checkout main
          command: git checkout main
      - browser-tools/install-chromedriver
      - node/install
      - node/install-packages
      - ruby/install-deps
      - build-docs
      - snapshot
  snapshot-branch:
    docker:
      - image: cimg/ruby:3.3-browsers
    steps:
      - checkout
      - browser-tools/install-chromedriver
      - node/install
      - node/install-packages
      - ruby/install-deps
      - build-docs
      - snapshot
  visual-regression:
    docker:
      - image: cimg/ruby:3.3-browsers
    environment:
      ONLY_VISUAL_REGRESSION_TEST: true
    steps:
      - checkout
      - browser-tools/install-chromedriver
      - node/install
      - node/install-packages
      - attach_workspace:
          at: tmp/screenshot/branches
      - run:
          name: Run visual regression test
          command: npm test
      - store_artifacts:
          path: tmp/screenshot/diff
          destination: results
      - store_test_results:
          path: tmp/screenshot/diff

ignore_main: &ignore_main
  filters:
    branches:
      ignore:
        - main

workflows:
  version: 2
  test:
    jobs:
      - lints
      - integration
  visual_regression:
    jobs:
      - snapshot-main:
          <<: *ignore_main
      - snapshot-branch:
          <<: *ignore_main
      - visual-regression:
          <<: *ignore_main
          requires:
            - snapshot-main
            - snapshot-branch
