title: Status Pill
status: beta
collated: true

variants:
  - name: default
    context:
      text: "success"
      modifier: success
  - name: warning
    context:
      text: "warning"
      modifier: warning
  - name: error
    context:
      text: "error"
      modifier: error
