title: 'borders'
status: draft
context:
  colors:
    - colorName: 'red'
    - colorName: 'blue'
    - colorName: 'gold'
    - colorName: 'green'
    - colorName: 'brightmint'
    - colorName: 'cream'
    - colorName: 'trueblack'
    - colorName: 'textblack'
    - colorName: 'darkgray'
    - colorName: 'mediumgray'
    - colorName: 'mediumgray-trans'
    - colorName: 'lightgray'
    - colorName: 'lightestgray'
    - colorName: 'white'
  borders:
    - border:
      borderName: '1px'
      borderCode: '1px'
    - border:
      borderName: '2px'
      borderCode: '2px'
    - border:
      borderName: '4px'
      borderCode: '05'
    - border:
      borderName: '8px'
      borderCode: '1'
  options:
    - option:
      optionName: border-x
      optionCode: bx
    - option:
      optionName: border-y
      optionCode: by
    - option:
      optionName: border-top
      optionCode: bt
    - option:
      optionName: border-right
      optionCode: br
    - option:
      optionName: border-bottom
      optionCode: bb
    - option:
      optionName: border-left
      optionCode: bl
