title: Button Outline
status: draft
collated: true
default: primary-outline
variants:
  - name: outline-primary
    context:
      isDefault: true
      isOutline: false
      isLink: false
      buttonStatus: btn-outline btn-primary
      buttonText: .btn-outline.btn-primary
  - name: outline-border
    context:
      isDefault: true
      isOutline: false
      isLink: false
      buttonStatus: btn-outline btn-border
      buttonText: .btn-outline.btn-border
