title: Button
status: draft
collated: true
default: primary
variants:
  - name: btn-primary
    context:
      isDefault: true
      isOutline: false
      isLink: false
      buttonStatus: btn-primary
      buttonText: .btn-primary
  - name: btn-border
    context:
      isDefault: true
      isOutline: false
      isLink: false
      buttonStatus: btn-border
      buttonText: .btn-border
  - name: btn-outline btn-primary
    context:
      isDefault: true
      isOutline: false
      isLink: false
      buttonStatus: btn-outline btn-primary
      buttonText: .btn-outline.btn-primary
  - name: btn-outline btn-border
    context:
      isDefault: true
      isOutline: false
      isLink: false
      buttonStatus: btn-outline btn-border
      buttonText: .btn-outline.btn-border
  - name: btn-wide btn-primary
    context:
      isDefault: true
      isOutline: false
      isLink: false
      buttonStatus: btn-wide btn-primary
      buttonText: .btn-wide.btn-primary
  - name: btn-wide btn-border
    context:
      isDefault: true
      isOutline: false
      isLink: false
      buttonStatus: btn-wide btn-border
      buttonText: .btn-wide.btn-border
  - name: btn-wide btn-outline btn-primary
    context:
      isDefault: true
      isOutline: false
      isLink: false
      buttonStatus: btn-wide btn-outline btn-primary
      buttonText: .btn-wide.btn-outline.btn-primary
  - name: btn-wide btn-outline btn-border
    context:
      isDefault: true
      isOutline: false
      isLink: false
      buttonStatus: btn-wide btn-outline btn-border
      buttonText: .btn-wide.btn-outline.btn-border
