title: 'spacing scale (base grid)'
status: draft
collated: true
context:
  patternMultiplier: '05'
  patternValue: 4px
variants:
  - name: default
    context:
      patternMultiplier: '05'
      patternValue: 4px
  - name: grid-1
    context:
      patternMultiplier: 1
      patternValue: 8px
  - name: grid-105
    context:
      patternMultiplier: 105
      patternValue: 12px
  - name: grid-2
    context:
      patternMultiplier: 2
      patternValue: 16px
  - name: grid-3
    context:
      patternMultiplier: 3
      patternValue: 24px
  - name: grid-4
    context:
      patternMultiplier: 4
      patternValue: 32px
  - name: grid-5
    context:
      patternMultiplier: 5
      patternValue: 40px
  - name: grid-6
    context:
      patternMultiplier: 6
      patternValue: 48px
  - name: grid-7
    context:
      patternMultiplier: 7
      patternValue: 56px
  - name: grid-8
    context:
      patternMultiplier: 8
      patternValue: 64px
  - name: grid-9
    context:
      patternMultiplier: 9
      patternValue: 72px
  - name: grid-10
    context:
      patternMultiplier: 10
      patternValue: 80px
