title: 'secondary color palette'
status: draft
context:
  colors:
    - color:
      colorName: 'gray'
      colorCode: '#5b616a'
    - color:
      colorName: 'gray-light'
      colorCode: '#dddddd'
    - color:
      colorName: 'teal'
      colorCode: '#00bfe7'
    - color:
      colorName: 'blue-mid'
      colorCode: '#1c5899'
    - color:
      colorName: 'blue-lightest'
      colorCode: '#f2f9ff'
